
name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to commit the changes

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "15.x"
          working-directory: "./ui-admin"
      - run: pwd
      - run: npm install
        working-directory: "./ui-admin"
      - run: npm run build
        working-directory: "./ui-admin"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui-admin/build
